### PR TITLE
Code review for JS best practices

### PR DESCRIPTION
**Pull request by olaishola05**
Peer to peer code review to check for JS best practice

### CODE REVIEW

**Review by Beardless-sheik — COMMENTED** [review]
Hi @netman5 . 

Great project. You followed all Best Practices and your code is very nicely organised! 

I only have one suggestion. Usually most source code is placed in the 'src' file. I see most of your modules are outside of it. I think it would be great to include all your source code to be built completely in the 'src' folder.

**Comment by olaishola05** [comment]
Thanks, @Beardless-sheik I'll affect the changes suggested as soon as possible.

**Comment by olaishola05** [comment]
Thanks, @Beardless-sheik I'll affect the changes suggested as soon as possible.

**Review by Beardless-sheik — APPROVED** [review]
Great work on the changes @netman5 !!

**Comment by olaishola05** [comment]
Thank You @Beardless-sheik :+1:

**Pull request merged**
